# Generated by Django 4.2.9 on 2024-01-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='model',
            field=models.FileField(blank=True, upload_to='models/'),
        ),
    ]
