# Generated by Django 4.2.9 on 2024-03-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0002_alter_classifier_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifier",
            name="min_threshold",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="sample",
            name="label",
            field=models.CharField(max_length=500),
        ),
    ]
