version: "3.7"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web/
      - ./cache/:/home/app/.cache
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$SQL_HOST/$POSTGRES_DB

  celery-beat:
    build: .
    command: celery -A core beat --loglevel DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./.env
    volumes:
      #      - .:/home/app/web/
      - ./cache/:/home/app/.cache
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$SQL_HOST/$POSTGRES_DB

  celery:
    build: .
    command: celery -A core worker --loglevel DEBUG --concurrency 4
    env_file:
      - ./.env
    volumes:
      #- .:/home/app/web/
      - ./cache/:/home/app/.cache
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$SQL_HOST/$POSTGRES_DB

  ml_api:
    build: .
    command: python manage.py launch 0.0.0.0
    volumes:
      #- .:/home/app/web/
      - model_storage:/home/app/store
      - ./cache/:/home/app/.cache
    env_file:
      - .env

  redis:
    image: redis:alpine

  cache:
    image: memcached:alpine


  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    expose:
      - 9001
    volumes:
      - minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    image: milvusdb/milvus
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus:/var/lib/milvus
    expose:
      - 19530
      - 9091
    depends_on:
      - "etcd"
      - "minio"

volumes:
  static:
  media:
  postgres_data:
  milvus:
  minio:
  etcd:
  model_storage:

