# Generated by Django 4.2.7 on 2023-11-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answering', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='realm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context.realm'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='webhook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answering.outputwebhook'),
        ),
        migrations.AddField(
            model_name='sampletask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='answering.tasktemplate'),
        ),
        migrations.AddField(
            model_name='processerror',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='answering.inputmessage'),
        ),
        migrations.AddField(
            model_name='outputmessage',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answering.inputmessage'),
        ),
        migrations.AddField(
            model_name='outputmessage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answering.tasktemplate'),
        ),
        migrations.AddField(
            model_name='messageclassification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answering.inputmessage'),
        ),
        migrations.AddField(
            model_name='messageclassification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='answering.tasktemplate'),
        ),
        migrations.AddField(
            model_name='inputmessage',
            name='inbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answering.inbox'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
