# Generated by Django 4.2.7 on 2023-11-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answering', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='name',
            field=models.CharField(default='Task Name', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputmessage',
            name='sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
