# Generated by Django 4.2.7 on 2023-11-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answering', '0003_tasktemplate_name_alter_inputmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='default_answer',
            field=models.TextField(blank=True),
        ),
    ]
