# Generated by Django 4.2.8 on 2023-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answering', '0004_tasktemplate_default_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='use_openai',
            field=models.BooleanField(default=True),
        ),
    ]
