# Generated by Django 4.2.9 on 2024-01-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answering', '0005_tasktemplate_use_openai'),
        ('answering', '0005_tasktemplate_use_openai_openaaiauth'),
    ]

    operations = [
    ]
