# Generated by Django 4.2.7 on 2023-11-05 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField()),
                ('meta', models.JSONField()),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_position', models.IntegerField()),
                ('length', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('language', models.CharField(max_length=10)),
                ('is_public', models.BooleanField()),
                ('embedding_model', models.CharField(choices=[('distiluse-base-multilingual-cased-v1', 'distiluse-base-multilingual-cased-v1'), ('paraphrase-multilingual-MiniLM-L12-v2', 'paraphrase-multilingual-MiniLM-L12-v2'), ('distiluse-base-multilingual-cased-v2', 'distiluse-base-multilingual-cased-v2'), ('paraphrase-multilingual-mpnet-base-v2', 'paraphrase-multilingual-mpnet-base-v2')], max_length=130)),
                ('embedding_dimension', models.IntegerField()),
                ('embedding_seq_length', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.realm'),
        ),
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.CharField(max_length=120)),
                ('start_urls', models.TextField(max_length=500)),
                ('allowed_domains', models.TextField(blank=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.realm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
