# Generated by Django 4.2.8 on 2023-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='embedding_dimension',
            field=models.IntegerField(default=384),
        ),
        migrations.AlterField(
            model_name='realm',
            name='embedding_model',
            field=models.CharField(choices=[('distiluse-base-multilingual-cased-v1', 'distiluse-base-multilingual-cased-v1'), ('paraphrase-multilingual-MiniLM-L12-v2', 'paraphrase-multilingual-MiniLM-L12-v2'), ('distiluse-base-multilingual-cased-v2', 'distiluse-base-multilingual-cased-v2'), ('paraphrase-multilingual-mpnet-base-v2', 'paraphrase-multilingual-mpnet-base-v2')], default='paraphrase-multilingual-MiniLM-L12-v2', max_length=130),
        ),
        migrations.AlterField(
            model_name='realm',
            name='embedding_seq_length',
            field=models.IntegerField(default=200),
        ),
    ]
