# Generated by Django 4.2.8 on 2023-12-06 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("context", "0001_initial"),
    ]

    operations = []
