# Generated by Django 4.2.9 on 2024-01-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='embedding_dimension',
        ),
        migrations.RemoveField(
            model_name='realm',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='realm',
            name='embedding_seq_length',
        ),
    ]
