# Generated by Django 4.2.9 on 2024-01-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_alter_realm_embedding_dimension_and_more'),
        ('context', '0002_remove_realm_embedding_dimension_and_more'),
    ]

    operations = [
    ]
